export const briefingContext = `
You answer questions about this group briefing. Stay inside these facts. If a question is outside them, say so in one sentence and answer only the part the briefing covers.

Article: Stephen Ansolabehere and Douglas Rivers, "Cooperative Survey Research," Annual Review of Political Science, 2013.
Speakers: Opening covers the question and why it matters. Abdullah covers the hypothesis. Amelie covers the method. Eric covers the data. Rahel covers the conclusion.

Research question: After matching and weighting, does YouGov's 2008 Cooperative Congressional Election Study recover the same party-vote relationship as the American National Election Studies, and the same presidential margins as the official returns? The 2008 vote is the test. The article is a methods paper.

Why it matters: A national sample of about 2,000 people cannot describe a state, a House district, or a small group. The 2008 CCES common sample is 32,800 interviews, shared by many teams. Face-to-face response rates were already falling. Douglas Rivers, a coauthor, founded Polimetrix, which YouGov bought in 2007, and was YouGov's chief scientist.

Hypothesis: Selection into the opt-in panel is ignorable given the matching variables (age, race, gender, education, party, registration, religion, news interest, and related traits). The prediction is about the matched, weighted sample. Published party slopes: CCES −0.313, ANES −0.312. Vote is coded +1 Obama, −1 McCain, 0 another named candidate. Party runs from 1 strong Democrat to 7 strong Republican. One step toward Republican lowers the predicted vote score by about 0.31 points on a scale from +1 Obama to −1 McCain. State errors should be a few points.

Method: The ANES is a face-to-face probability sample, interviewed at home before the election and again after. It is not the exit poll. The post-election vote item is V085044a. The post weight is V080102. The CCES is a volunteer internet panel. About 50,800 people finished the pre-election interview. Matching keeps 32,800. The released weight is V201. It averages 1 and, in this file, runs from 0.30 to 6.49.

A target row is one specific person-record drawn from the 2006 American Community Survey, stratified by age, race, gender, and education. Registration and past turnout are copied from the 2004 Current Population Survey. Religion, party, ideology, and news interest are copied from the 2007 Pew Religious Landscape Survey. Completed interviews were invited with a five-way cross-classification: age × gender × race × education × state. There is a search per target person. The closest panelist is kept even if the match is imperfect. The distance function fmatch is in the 2008 study guide, not in this project's analysis.py. It is a sum of penalties, and the lowest total wins. It is not a similarity score where the highest total wins. Penalties: race mismatch 10, registration matrix times 4, gender 1.5, party 1.5, ideology 1, region 1, each year of age costs 1/30, each year of schooling costs 1/6, one step across the age groups 18–29, 30–64, and 65+ costs 0.5, religion mismatch 0.5, news interest 0.5. Income distance is divided by 15, marital status by 4, church attendance by 10, and metro status by 2.

Worked example from that function. Target: woman, age 34, white, 16 years of school, South, married, Democrat, Catholic, registered, income held fixed. A woman age 40 who matches every other listed trait scores 6/30 = 0.20. A man who matches every other trait scores 1.5. A woman of a different race who matches every other trait scores 10. The age-40 woman is kept.

The frame is U.S. citizens, including nonvoters. Registration keeps unregistered adults in the sample. It does not drop low-turnout groups to imitate the electorate. After matching, a logistic propensity model uses age, years of education, gender, and turnout. Scores are grouped into deciles. Gender, race, education, and age are raked to the frame. Weights above 7 are trimmed, then every weight is divided by the same constant so the weights sum to the sample size and average 1. The 7 is a ceiling on the survey weight. The study guide does not cap how many times one panelist may be selected at 7. In the released file V201 runs from 0.30 to 6.49 because the division comes after the cut. Dividing every weight by the same constant does not change a percentage or a slope. An Obama voter weighted 2 and a McCain voter weighted 1 put Obama at two thirds either before or after that division. On the full CCES list, party is −0.314 with the weights and −0.320 with every weight set to 1. Removing the ANES weight moves party from −0.317 to −0.293.

ANES and CCES both record what people said in an interview. The exit poll is a separate election-day survey. This replication does not load exit-poll microdata. The state check compares the CCES two-party share with certified returns in Prez by State.csv. That check is about how the vote split, not the turnout rate. After weighting, 70.7 percent of the CCES say they voted. Eligible-citizen turnout in 2008 was about 62 percent.

Data: Shared weighted least squares, covariates in both files (party, age, Black, Hispanic, other race). Party slope −0.317 in the CCES (N = 23,681, standard error 0.002) and −0.317 in the ANES (N = 1,538, standard error 0.010). Published table: −0.313 and −0.312. Full CCES model party slope −0.314 (N = 22,223, R² = 0.642) against published −0.313 (N = 25,814). Age per 10 years: CCES −0.040, ANES −0.050. Black: +0.260 versus +0.325. Hispanic: +0.063 versus +0.159. Other race: +0.014 versus +0.259. Those race coefficients are partial effects, holding party and age fixed. A CCES coefficient closer to zero means race adds less to the predicted vote score once party and age are known. It does not mean the group cast fewer votes for Obama. Standard errors: Black 0.015 versus 0.045, Hispanic 0.022 versus 0.055, other race 0.024 versus 0.097. The Black intervals overlap. Hispanic barely does. Other race does not, and the ANES other-race cell is 48 two-party voters. Weights off: CCES party −0.320, ANES party −0.293. Two-party Obama share, Obama among Obama and McCain. All: CCES 53.9, ANES 54.9, certified national count 53.7. White: CCES 46.5 (n 19,889), ANES 44.2 (n 799), exit-poll two-party 43.9 from published 43 percent Obama and 55 percent McCain. Black: CCES 96.3 (n 1,361), ANES 99.6 (n 418), exit-poll two-party 96.0 from published 95 and 4. Hispanic: CCES 65.8 (n 1,191), ANES 77.0 (n 275), exit-poll two-party 68.4 from published 67 and 31. The article cites the published 67. Other race: CCES 52.3 (n 1,144), ANES 80.1 (n 48), exit-poll Asian-plus-other two-party 66.4 from Asian 62/35 (2 percent of the electorate) and other 66/31 (3 percent). The exit poll is the National Election Pool, Edison/Mitofsky, because the certified count has no race breakdown. The election confirms the CCES for the national share, Black voters, and Hispanic voters, and the ANES for white voters. It confirms neither survey for other race. Fifty states: CCES minus official two-party Democratic share averages +1.00 points, RMSE 3.43. The article reports +0.27 and 2.43.

Extensions, which are ours and not in the 2013 article: House party slope −0.298, Senate −0.306, governor −0.289. Adding ideology and three issue items cuts the presidential party slope from −0.314 to −0.170 on the same 17,318 respondents. More informed respondents are slightly more partisan.

Conclusion: The article says a matched, weighted cooperative internet sample can recover the electoral relationships of a face-to-face probability survey, for the processed sample, under ignorability. Our replication reproduces the party result. The state check agrees in direction and size, not to the published decimals.
`.trim();
